name: Build RNNoise DLL

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@v3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -A x64
          cmake --build . --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rnnoise-dll
          path: build/Release/*.dll
